#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi
xinit /var/www/piboard/scripts/startbrowser &
#su pi -c 'node /home/pi/PI-Board-Node/app.js < /dev/null &'
su - root -c "NODE_ENV=production /usr/local/bin/forever start /var/www/piboard/app.js"

exit 0
